services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    container_name: api
    build:
      context: ../api
      dockerfile: ../infra/docker/api.Dockerfile
    command: npm run dev
    depends_on:
      - postgres
    env_file:
      - ../infra/.env
    ports:
      - "4000:4000"
    volumes:
      - ../api:/usr/src/app
      - /usr/src/app/node_modules

  web:
    container_name: web
    build:
      context: ../web
      dockerfile: ../infra/docker/web.Dockerfile
    command: npm run dev -- --host
    depends_on:
      - api
    env_file:
      - ../infra/.env
    ports:
      - "5173:5173"
    volumes:
      - ../web:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  pgdata:
